spec:
 template:
   spec:
     containers:
       - env:
         - name: JAVA_OPTIONS
           value: "-Xms512m -Xmx1G -Dapp=hello-vertx -Dvertx.hazelcast.config=classpath:hazelcast.xml"
         - name: VERTX_CONFIG_PATH
           value: "conf/application.yaml"
         - name: HZ_MODE
           value: "file"