kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/henriorespati/hello-vertx.git'
  name: hello-vertx-s2i
  labels:
    app: hello-vertx
    app.kubernetes.io/name: hello-vertx
    app.kubernetes.io/part-of: com.redhat.rharyanto.hellovertx
    group: com.redhat.rharyanto.hellovertx
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-vertx:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/jkube/jkube-java-17:0.0.23'
  source:
    type: Binary
  runPolicy: Serial
