kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/henriorespati/hello-vertx.git'
  name: hello-vertx
  labels:
    app: hello-vertx
    app.kubernetes.io/name: hello-vertx
    app.kubernetes.io/part-of: com.redhat.rharyanto.hellovertx
    group: com.redhat.rharyanto.hellovertx
spec:
  lookupPolicy:
    local: true
