apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-vertx
spec:
  template:
    spec:
      containers:
      - name: vertx
        image: image-registry.openshift-image-registry.svc:5000/hello-vertx-dev/hello-vertx:latest
        env:
        - name: VERTX_CONFIG_PATH
          value: conf/application.dev.yaml
